# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-19 05:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 19, 5, 49, 6, 920791)),
        ),
        migrations.AlterField(
            model_name='downvote',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 19, 5, 49, 6, 923303)),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 19, 5, 49, 6, 921396)),
        ),
        migrations.AlterField(
            model_name='topic',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 19, 5, 49, 6, 920293)),
        ),
        migrations.AlterField(
            model_name='upvote',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 19, 5, 49, 6, 922782)),
        ),
    ]
